{{- if and .Values.networkPolicies.enabled .Values.gotenberg.enabled }}
# Allow scm to reach gotenberg
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "scm.gotenbergName" . }}-allow-scm
  labels:
    {{- include "scm.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "scm.gotenbergSelectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Release.Namespace }}
          podSelector:
            matchLabels:
              {{- include "scm.scmSelectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 3000
{{- end }}