version: '3'
services:
  zalenium:
    image: dosel/zalenium
    ports:
    - "4444:4444"
    volumes:
    - ./target:/home/seluser/videos
    - /var/run/docker.sock:/var/run/docker.sock
    command: start
