global:
  imagePullSecrets:
    - name: "ces-container-registries"

networkPolicies:
  enabled: true
  gateway:
    matchLabels:
      k8s.cloudogu.com/component.name: k8s-ces-gateway
  serviceAccountOperator:
    matchLabels:
      k8s.cloudogu.com/component.name: service-account-operator

extraLabels: {}

scm:
  replicas: 1

  image:
    registry: registry.cloudogu.com
    repository: official/scm
    tag: 3.11.10-1
  imagePullPolicy: IfNotPresent

  podSecurityContext:
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch

  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    capabilities:
      drop:
        - ALL

  resourceLimits:
    memory: 500Mi
  resourceRequests:
    cpu: 126m
    memory: 500Mi

  persistence:
    size: 2Gi
    storageClassName: ""

  exposition:
    externalPort: 2222
  service:
    ports:
      web:
        protocol: TCP
        port: 8080
        targetPort: web
      ssh:
        protocol: TCP
        port: 2222
        targetPort: ssh
      sa-manager:
        protocol: TCP
        port: 8090
        targetPort: sa-manager

  extraVolumeMounts: []
  extraEnv: []
  extraVolumes: []
  extraInitContainers: []

  tolerations: []
  affinity: {}
  nodeSelector: {}

  # Dogu-Configuration
  configuration:
    meta:
      global:
        name: global-config
        key: config.yaml
      normal:
        key: normal
      sensitive:
        key: sensitive
    normal: # config.yaml style; slash-keys from dogu.json become nested keys
      logging:
        root: "WARN"
      container_config:
        java_max_ram_percentage: "25.0"
        java_min_ram_percentage: "50.0"

  # scm-sa-manager sidecar
  saManager:
    image:
      registry: registry.cloudogu.com
      repository: k8s/service-account-producer-sidecar
      tag: "0.1.3"
    imagePullPolicy: IfNotPresent
    logLevel: INFO
    resourceRequests:
      cpu: 50m
      memory: 64Mi
    resourceLimits:
      memory: 64Mi

# Self-contained gotenberg
gotenberg:
  image:
    registry: docker.io
    repository: gotenberg/gotenberg
    tag: "8.34.0"
  imagePullPolicy: IfNotPresent
  resourceRequests:
    cpu: 15m
    memory: 200Mi
  resourceLimits:
    memory: 200Mi
