apiVersion: v1
kind: Service
metadata:
  name: {{ include "scm.name" . }}
  labels:
    {{- include "scm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "scm.scmSelectorLabels" . | nindent 4 }}
  ports:
    {{- range $name, $value := .Values.scm.service.ports }}
    - name: {{ $name | quote }}
      {{- toYaml $value | nindent 6 }}
    {{- end }}
