# Registers scm as a ServiceAccountProducer
apiVersion: k8s.cloudogu.com/v2
kind: ServiceAccountProducer
metadata:
  name: {{ include "scm.name" . }}
  labels:
    {{- include "scm.labels" . | nindent 4 }}
spec:
  producer: {{ include "scm.name" . }}
  http:
    endpoint: "http://{{ include "scm.name" . }}.{{ .Release.Namespace }}.svc:{{ (index .Values.scm.service.ports "sa-manager").port }}/serviceaccounts"
    authSecret:
      name: {{ include "scm.fullname" . }}-sa-manager-auth
      key: apiKey
    priority: 1
    params:
      attributes:
        permission:
          type: string
          enum: [ "ro", "rw", "admin" ]
          description: The permission to grant to the service account. Either "ro", "rw", or "admin".
    return:
      username:
        description: Generated technical username for the service account.
      password:
        description: Password for the generated service account.
